test:
  extends:
    file: base.yml
    service: base
  ports:
    - "3005"
  container_name: tilestrata-forest-change-server
  environment:
    NODE_ENV: test
    CT_URL: http://mymachine:9000
  command: test
